### PR TITLE
Refactory files

### PR DESCRIPTION
**Pull request by jzunigarce**
**Detail**

- The server is separated from the application. Using server.js for init the server and using app.js for create the application. The startup is server.js
- Create single file for call .env variables on server. src/server/config/variables.js
- Separate models and schemas. Now the schema is placed on the src/server/schema and the model on src/server/models. The model call to schema.

### CODE REVIEW

**Review by gbowne1 — CHANGES_REQUESTED** [review]
This has conflicts.  But should work once resolved. 

I would also like to propose we insert passport.js to handle some stuff as well and possibly axios for the web side.  

We still need to have working unit, e2e, integration tests.  Eventually I think we shoukd require passing tests to merge.  I made some tests in /tests but they don't work yet afaik

**Comment by jzunigarce** [comment]
I fix the problem. I removed cookieSession as we had another way to generate a session server side, however if required cookieSession can be added.

**Comment by gbowne1** [comment]
Yes  looks like it fixed. merged.

**Comment by gbowne1** [comment]
Cookie session might help though

**Comment by jzunigarce** [comment]
I currently use cookie-parser, another middleware

**Pull request merged**
