### PR TITLE
Implement middlewares server

### PR DESCRIPTION
**Pull request by jzunigarce**
**Details**

- Install helment dependecie
- Implement and config morgan middleware
- Implement and config helment middleware

### CODE REVIEW

**Comment by gbowne1** [comment]
This looks good. 

Merging.

**Comment by gbowne1** [comment]
Today, I added boilerplate tests for mocha and chai to use

**Comment by gbowne1** [comment]
I think we should move from ejs template engine to just serving the static files

So we would need to add:

app.use(express.static('public'))

and 

remove the app.engine('html', require('ejs').renderFile); since all of our assets are coming from /public in the client and we are not using pug, ejs etc.

**Comment by jzunigarce** [comment]
Static files just represent data and are manipulated with js? or render variables from the backend?

**Comment by gbowne1** [comment]
Yes.  The html, css and js of the routes other than the dashboard all interact with the database through forms.  And also display returned values from the database in a table. 

The /data/*.json all fill dropdown selects with values. I need to finish up and add the last of that json data.

The dashboard is controlled by the app.js and index.js and the server.js 

Click on a button on a dashboard card will switch the routes using js.  

Models need to be finished as well.

**Pull request merged**
